# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 13:20
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=10)),
                ('type', models.IntegerField(default=Decimal('0'), null=True)),
                ('name', models.CharField(max_length=64)),
                ('nickName', models.CharField(max_length=50)),
                ('bankName', models.CharField(max_length=50)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
                ('accountWithBank', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('modifiedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=10)),
                ('txid', models.CharField(max_length=64, null=True)),
                ('bankId', models.CharField(max_length=50, null=True)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('fee', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('feeRate', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('feeTxid', models.CharField(max_length=64, null=True)),
                ('feeType', models.PositiveSmallIntegerField(default=0)),
                ('note', models.CharField(max_length=128)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('modifiedTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        )
    ]
