# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 09:52
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=10)),
                ('type', models.IntegerField(default=Decimal('0'), null=True)),
                ('name', models.CharField(max_length=64)),
                ('nickName', models.CharField(max_length=50)),
                ('bankName', models.CharField(max_length=50)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
                ('accountWithBank', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('modifiedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=10)),
                ('txid', models.CharField(max_length=64, null=True)),
                ('bankId', models.CharField(max_length=50, null=True)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('fee', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('feeRate', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('feeTxid', models.CharField(max_length=64, null=True)),
                ('feeType', models.PositiveSmallIntegerField(default=0)),
                ('note', models.CharField(max_length=128)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('modifiedTime', models.DateTimeField(auto_now=True)),
                ('error', models.CharField(max_length=128)),
                ('randomStr', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignCheck',
            fields=[
                ('signature', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('pubkey', models.CharField(max_length=66)),
            ],
        ),
        migrations.DeleteModel(
            name='Recharge',
        ),
        migrations.RenameField(
            model_name='withdraw',
            old_name='feeFirstValue',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='withdraw',
            old_name='feeFirst',
            new_name='feeTxid',
        ),
        migrations.RenameField(
            model_name='withdraw',
            old_name='signature',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='address',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='alipayAccount',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='alipayAccountName',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='feeSecond',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='feeSecondValue',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='hexPubkey',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='nonce',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='operatorId',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='receiveValue',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='value',
        ),
        migrations.AddField(
            model_name='withdraw',
            name='bankId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='feeType',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='sort',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='uid',
            field=models.CharField(max_length=10),
        ),
    ]
